name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run integration tests
        run: make ci-test

      - name: Cleanup
        if: always()
        run: make fclean