name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          cat > .env <<EOF
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_API_NAME=${{ vars.DB_API_NAME}}
          DB_API_USER=${{ vars.DB_API_USER }}
          DB_API_PWD=${{ secrets.DB_API_PWD }}
          EOF

      - name: Run integration tests
        run: make ci-test

      - name: Cleanup
        if: always()
        run: make fclean