services:
  kpi-api:
    build: ./kpi_api
    container_name: kpi-api
    ports:
      - "8000:8000"
    networks:
      - hr-process-helper
    profiles:
      - app
    environment:
      OTEL_SERVICE_NAME: kpi-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    env_file:
      - ../.env
    depends_on:
      database:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      JAEGER_UI_CONFIG_FILE: /etc/jaeger/ui-config.json
    volumes:
      - ./jaeger/jaeger-ui.json:/etc/jaeger/ui-config.json:ro
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - hr-process-helper
    profiles:
      - app

  mcp-server:
    build: ./mcp_server
    container_name: mcp-server
    ports:
      - "8001:8001"
    networks:
      - hr-process-helper
    profiles:
      - app
    environment:
      OTEL_SERVICE_NAME: mcp-server
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

  agent-system:
    build: ./agent_system
    container_name: agent-system
    ports:
      - "8002:8002"
    networks:
      - hr-process-helper
    env_file:
      - ../.env
    environment:
      OTEL_SERVICE_NAME: agent-system
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    profiles:
      - app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:8080"
    networks:
      - hr-process-helper
    profiles:
      - app


  database:
    container_name: database
    build: ./database
    env_file:
      - ../.env
    networks:
      - hr-process-helper
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    profiles:
      - app

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_API_USER} -d ${DB_API_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ci-test:
    container_name: ci-test
    build: ./ci_test
    networks:
      - hr-process-helper
    profiles:
      - test

volumes:
  postgres_data:   

networks:
  hr-process-helper:
    driver: bridge